package brobata.physiboard.core.actions.emoji

import brobata.physiboard.core.keys.KeyId

/**
 * The five Fitzpatrick skin-tone modifiers, plus "no tone". [storedValue] is the
 * `emoji_default_skin_tone` preference string. spec: expansion-clipboard-pickers-launcher.md SS4.7.
 */
enum class SkinTone(val storedValue: String, val modifier: String?, val label: String) {
    NONE("none", null, "No tone"),
    LIGHT("light", "🏻", "Light"),
    MEDIUM_LIGHT("medium_light", "🏼", "Medium-light"),
    MEDIUM("medium", "🏽", "Medium"),
    MEDIUM_DARK("medium_dark", "🏾", "Medium-dark"),
    DARK("dark", "🏿", "Dark"),
    ;

    companion object {
        /** An unknown or missing stored value is no tone. */
        fun fromStored(stored: String?): SkinTone = entries.firstOrNull { it.storedValue == stored } ?: NONE

        /** The five real tones, in modifier order (U+1F3FB to U+1F3FF). */
        val TONES: List<SkinTone> = listOf(LIGHT, MEDIUM_LIGHT, MEDIUM, MEDIUM_DARK, DARK)
    }
}

/**
 * Which emoji take a skin tone, and how to tone one. spec: expansion-clipboard-pickers-launcher.md
 * SS4.7. The list comes from Unicode's emoji-test.txt ([SkinToneTable], generated by
 * scripts/build_skin_tone_table.py): an emoji is toneable only when Unicode lists a form of it
 * with every person in the same tone. So a single person (👋), a person with a role or a
 * direction (👩‍💻, 🚶‍➡️), and the couples and pairs that Unicode tones as a whole (🧑‍🤝‍🧑, 💏,
 * 👩‍❤️‍👨) are toneable, and a family (👨‍👩‍👧), a heart, a flag or anything else is left
 * exactly as it is: applying a modifier by rule to a sequence Unicode never toned would produce
 * a broken sequence that renders as separate glyphs.
 *
 * Mixed tones for a pair (🧑🏻‍🤝‍🧑🏿) are not produced here; the picker's long-press popup still
 * lists every combination the emoji assets carry.
 */
object SkinTones {
    private const val LIGHT_MODIFIER: String = "🏻"
    private const val VS16: Char = '️'

    private class Forms(val untoned: String, val light: String)

    private val byKey: Map<String, Forms> by lazy {
        val out = HashMap<String, Forms>(SkinToneTable.SIZE * 2)
        for (line in SkinToneTable.ENTRIES) {
            val space = line.indexOf(' ')
            if (space <= 0) continue
            val untoned = line.substring(0, space)
            val light = line.substring(space + 1).trim()
            out[key(untoned)] = Forms(untoned, light)
        }
        out
    }

    /** The emoji with every tone modifier and every VS16 removed: ☝, ☝️ and ☝🏽 share one key. */
    private fun key(emoji: String): String {
        val sb = StringBuilder(emoji.length)
        var i = 0
        while (i < emoji.length) {
            val cp = emoji.codePointAt(i)
            if (cp != VS16.code && modifierTone(cp) == null) sb.appendCodePoint(cp)
            i += Character.charCount(cp)
        }
        return sb.toString()
    }

    private fun modifierTone(codePoint: Int): SkinTone? = when (codePoint) {
        0x1F3FB -> SkinTone.LIGHT
        0x1F3FC -> SkinTone.MEDIUM_LIGHT
        0x1F3FD -> SkinTone.MEDIUM
        0x1F3FE -> SkinTone.MEDIUM_DARK
        0x1F3FF -> SkinTone.DARK
        else -> null
    }

    private fun formsOf(emoji: String): Forms? = if (emoji.isEmpty()) null else byKey[key(emoji)]

    /** Whether Unicode tones [emoji] as a whole (in any of its forms, toned or not). */
    fun isToneable(emoji: String): Boolean = formsOf(emoji) != null

    /**
     * The tone [emoji] already carries: [SkinTone.NONE] when it has no modifier, the tone when
     * every modifier in it is the same one, null for a mixed combination (🧑🏻‍🤝‍🧑🏿).
     */
    fun toneOf(emoji: String): SkinTone? {
        var found: SkinTone? = null
        var i = 0
        while (i < emoji.length) {
            val cp = emoji.codePointAt(i)
            val tone = modifierTone(cp)
            if (tone != null) {
                if (found != null && found != tone) return null
                found = tone
            }
            i += Character.charCount(cp)
        }
        return found ?: SkinTone.NONE
    }

    /**
     * [emoji] in [tone]: the untoned form for [SkinTone.NONE], otherwise the form with every
     * person in that tone. An emoji that does not take tones comes back unchanged, so this is
     * safe to call on anything a key or a picker inserts.
     */
    fun apply(emoji: String, tone: SkinTone): String {
        val forms = formsOf(emoji) ?: return emoji
        val modifier = tone.modifier ?: return forms.untoned
        return forms.light.replace(LIGHT_MODIFIER, modifier)
    }

    /**
     * spec SS4.7: what the default tone does to an emoji about to be inserted or shown. An emoji
     * that already carries a tone (the user picked one) keeps it; an untoned one that takes tones
     * gets [default]; anything else is unchanged. [SkinTone.NONE] changes nothing.
     */
    fun withDefault(emoji: String, default: SkinTone): String {
        if (default == SkinTone.NONE) return emoji
        if (toneOf(emoji) != SkinTone.NONE) return emoji
        return apply(emoji, default)
    }

    /**
     * The chooser's choices for [emoji]: the untoned form then the five tones, in modifier order,
     * or an empty list when the emoji does not take tones. spec SS4.7.
     */
    fun forms(emoji: String): List<String> {
        if (formsOf(emoji) == null) return emptyList()
        return listOf(apply(emoji, SkinTone.NONE)) + SkinTone.TONES.map { apply(emoji, it) }
    }

    /** How many emoji the table lists; for tests and the spec's numbers. */
    val size: Int get() = byKey.size
}

/**
 * The hardware-key skin-tone chooser of spec SS4.7 as a pure model. A letter that commits a
 * toneable emoji (an Emoji page key, a Sym chord, the picker's page) arms a hold; if the same key
 * is still down once [thresholdMs] has passed, the chooser opens with that emoji's six forms.
 * While it is open the six forms are picked by the keys printed 0 to 5 (the Titan's device layer:
 * Q, W, E, R, S, D on both Titan legends) or by the digit keys of a keyboard that has them. Back
 * closes it without a change; any other key closes it and is typed as usual.
 */
object SkinToneChooser {

    /** A press that committed [committed], a toneable emoji, and may still turn into a hold. */
    data class Hold(val key: KeyId, val committed: String, val armedAtMs: Long, val thresholdMs: Long) {
        fun deadlineMs(): Long = armedAtMs + thresholdMs
        fun hasFired(nowMs: Long): Boolean = nowMs - armedAtMs >= thresholdMs
    }

    /** What one key-down does while the chooser is open. */
    sealed class KeyOutcome {
        /** Replace the committed emoji with [form] and close; the key and its release are consumed. */
        data class Pick(val form: String) : KeyOutcome()

        /** Close without a change; the key and its release are consumed (Back, or a repeat of the held key). */
        object Dismiss : KeyOutcome()

        /** The held key's own auto-repeat: consumed, the chooser stays open. */
        object Swallow : KeyOutcome()

        /** Close, and let the key do what it would have done. */
        object CloseAndPassOn : KeyOutcome()
    }

    /** The digit 0 to 5 a key stands for: its device-layer character when that is a digit, or its own digit. */
    fun digitFor(deviceLayerText: String?, ownDigit: Char?): Int? {
        val fromLayer = deviceLayerText?.singleOrNull()?.takeIf { it in '0'..'5' }
        val digit = fromLayer ?: ownDigit?.takeIf { it in '0'..'5' } ?: return null
        return digit - '0'
    }

    /**
     * spec SS4.7's key table. [isBack] is the Back key; [isHeldKeyRepeat] is an auto-repeat of the
     * key that opened the chooser; [digit] is [digitFor]'s answer for this key.
     */
    fun onKeyDown(forms: List<String>, isBack: Boolean, isHeldKeyRepeat: Boolean, digit: Int?): KeyOutcome = when {
        isHeldKeyRepeat -> KeyOutcome.Swallow
        isBack -> KeyOutcome.Dismiss
        digit != null && digit in forms.indices -> KeyOutcome.Pick(forms[digit])
        else -> KeyOutcome.CloseAndPassOn
    }

    /**
     * Whether the text just committed for a fresh press arms a hold: it must be one emoji that
     * takes tones. A letter, a word or a heart never does.
     */
    fun arms(committed: String): Boolean = committed.isNotBlank() && SkinTones.isToneable(committed.trim())
}
