#!/usr/bin/env python3
"""Generates the emoji picker's assets from Unicode's emoji-test.txt.

spec: expansion-clipboard-pickers-launcher.md SS4.1 ("The assets are generated by a pinned
script from Unicode Emoji 17.0 emoji-test.txt and the CLDR 48.2.1 JSON annotations").

Usage: build_emoji_assets.py <emoji-test.txt> <out-dir> [<cldr-annotations-dir>]

Writes <out-dir>/emoji/<CATEGORY>.txt (one base per line, its variants after it, space
separated), <out-dir>/emoji/minApi.txt (one line per API level: the level then the emoji that
first shipped at that level) and <out-dir>/emoji_search/en.tsv (emoji, CLDR short name, keywords).
When a CLDR annotations directory (the JSON `annotations/<locale>/annotations.json` tree) is
given, one <locale>.tsv is written per shipped locale from it; otherwise only en.tsv is written
from the short names in emoji-test.txt itself.
"""
import json
import os
import re
import sys

GROUPS = {
    "Smileys & Emotion": "SMILEYS_AND_EMOTION",
    "People & Body": "PEOPLE_AND_BODY",
    "Animals & Nature": "ANIMALS_AND_NATURE",
    "Food & Drink": "FOOD_AND_DRINK",
    "Travel & Places": "TRAVEL_AND_PLACES",
    "Activities": "ACTIVITIES",
    "Objects": "OBJECTS",
    "Symbols": "SYMBOLS",
    "Flags": "FLAGS",
}
# spec SS4.1: the API map. Everything at or before E3.0 shipped by API 23.
API_BY_VERSION = {
    "0.6": 23, "0.7": 23, "1.0": 23, "2.0": 23, "3.0": 23,
    "4.0": 24, "5.0": 26, "11.0": 28, "12.0": 29, "12.1": 29, "13.0": 30, "13.1": 31,
    "14.0": 32, "15.0": 33, "15.1": 34, "16.0": 35,
}
SKIN_TONES = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}
LOCALES = ["de", "en", "es", "fr", "hy", "it", "pl", "ru", "uk"]
LINE = re.compile(r"^([0-9A-F ]+?)\s*;\s*(fully-qualified|component)\s*#\s*(\S+)\s+E(\d+\.\d+)\s+(.*)$")


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    source, out = sys.argv[1], sys.argv[2]
    cldr = sys.argv[3] if len(sys.argv) > 3 else None
    categories = {cid: [] for cid in GROUPS.values()}
    names = {}
    min_api = {}
    group = None
    with open(source, encoding="utf-8") as f:
        for raw in f:
            if raw.startswith("# group:"):
                group = GROUPS.get(raw.split(":", 1)[1].strip())
                continue
            m = LINE.match(raw.strip())
            if not m or group is None:
                continue
            cps, status, emoji, version, name = m.groups()
            if status != "fully-qualified":
                continue
            codepoints = [int(c, 16) for c in cps.split()]
            api = API_BY_VERSION.get(version)
            if api is not None:
                min_api.setdefault(api, []).append(emoji)
            tones = [c for c in codepoints if c in SKIN_TONES]
            if tones:
                base_cps = [c for c in codepoints if c not in SKIN_TONES]
                base = "".join(chr(c) for c in base_cps)
                # A toned form whose base is a fully-qualified line becomes that base's variant;
                # a multi-person tone combination whose base is not listed is dropped.
                for entry in categories[group]:
                    if entry[0] == base:
                        entry.append(emoji)
                        break
                continue
            categories[group].append([emoji])
            names[emoji] = name
    os.makedirs(os.path.join(out, "emoji"), exist_ok=True)
    os.makedirs(os.path.join(out, "emoji_search"), exist_ok=True)
    for cid, entries in categories.items():
        with open(os.path.join(out, "emoji", cid + ".txt"), "w", encoding="utf-8") as f:
            for entry in entries:
                f.write(" ".join(entry) + "\n")
    with open(os.path.join(out, "emoji", "minApi.txt"), "w", encoding="utf-8") as f:
        for api in sorted(min_api):
            f.write(str(api) + " " + " ".join(min_api[api]) + "\n")
    all_bases = [e[0] for entries in categories.values() for e in entries]
    if cldr:
        for locale in LOCALES:
            path = os.path.join(cldr, locale, "annotations.json")
            if not os.path.exists(path):
                continue
            ann = json.load(open(path, encoding="utf-8"))["annotations"]["annotations"]
            write_tsv(os.path.join(out, "emoji_search", locale + ".tsv"), all_bases, lambda e: (ann.get(e, {}).get("tts", [""])[0], ann.get(e, {}).get("default", [])))
    else:
        write_tsv(os.path.join(out, "emoji_search", "en.tsv"), all_bases, lambda e: (names.get(e, ""), [w for w in re.split(r"[ :,-]+", names.get(e, "")) if w]))


def write_tsv(path, bases, terms):
    with open(path, "w", encoding="utf-8") as f:
        for emoji in bases:
            name, keywords = terms(emoji)
            f.write(f"{emoji}\t{name}\t{'|'.join(keywords)}\n")


if __name__ == "__main__":
    main()
