package it.palsoftware.pastiera

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.Bundle
import android.provider.Settings
import android.view.KeyEvent
import android.view.inputmethod.InputMethodManager
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.asPaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.IntrinsicSize
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBars
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Code
import androidx.compose.material.icons.filled.Keyboard
import androidx.compose.material.icons.filled.Mic
import androidx.compose.material.icons.filled.Language
import androidx.compose.material.icons.filled.LightMode
import androidx.compose.material.icons.filled.Palette
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material.icons.filled.Spellcheck
import androidx.compose.material.icons.filled.Update
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import it.palsoftware.pastiera.inputmethod.DeviceSpecific
import it.palsoftware.pastiera.inputmethod.EmbeddedAdbShell
import it.palsoftware.pastiera.inputmethod.KeyboardEventTracker
import it.palsoftware.pastiera.inputmethod.NotificationHelper
import it.palsoftware.pastiera.inputmethod.subtype.AdditionalSubtypeUtils.localeString
import it.palsoftware.pastiera.ui.CustomTopBar
import it.palsoftware.pastiera.ui.theme.PastieraTheme
import it.palsoftware.pastiera.update.UpdateCheckWorker
import it.palsoftware.pastiera.update.checkForUpdate
import it.palsoftware.pastiera.update.shouldUseGithubUpdateChecks
import it.palsoftware.pastiera.update.showUpdateDialog
import kotlinx.coroutines.delay
import java.util.Locale

class MainActivity : LocalizedComponentActivity() {

    data class KeyEventInfo(
        val keyCode: Int,
        val keyCodeName: String,
        val action: String,
        val unicodeChar: Int,
        val isAltPressed: Boolean,
        val isShiftPressed: Boolean,
        val isCtrlPressed: Boolean
    )

    private fun remapHardwareEvent(keyCode: Int, event: KeyEvent?): Pair<Int, KeyEvent?> {
        val remapped = DeviceSpecific.remapHardwareKeyEvent(
            keyCode,
            event,
            SettingsManager.getPhysicalKeyboardProfileOverride(this)
        )
        return remapped.keyCode to remapped.event
    }

    override fun onKeyDown(keyCode_: Int, event_: KeyEvent?): Boolean {
        val (keyCode, event) = remapHardwareEvent(keyCode_, event_)
        // Notify only events that are not output keycodes generated by the service.
        // Output keycodes (DPAD, TAB, PAGE_UP, PAGE_DOWN, ESCAPE) without modifiers
        // are generated by the service and the original event with output has already been reported.
        if (event != null) {
            val isOutputKeyCode = keyCode in listOf(
                KeyEvent.KEYCODE_DPAD_UP,
                KeyEvent.KEYCODE_DPAD_DOWN,
                KeyEvent.KEYCODE_DPAD_LEFT,
                KeyEvent.KEYCODE_DPAD_RIGHT,
                KeyEvent.KEYCODE_TAB,
                KeyEvent.KEYCODE_PAGE_UP,
                KeyEvent.KEYCODE_PAGE_DOWN,
                KeyEvent.KEYCODE_ESCAPE
            )
            val hasModifiers = event.isAltPressed || event.isShiftPressed || event.isCtrlPressed

            // Ignora i keycode di output senza modificatori (sono generati dal servizio)
            if (!isOutputKeyCode || hasModifiers) {
                KeyboardEventTracker.notifyKeyEvent(keyCode, event, "KEY_DOWN", origin = "activity")
            }
        }
        return super.onKeyDown(keyCode, event)
    }

    override fun onKeyUp(keyCode_: Int, event_: KeyEvent?): Boolean {
        val (keyCode, event) = remapHardwareEvent(keyCode_, event_)
        // Notify only events that are not output keycodes generated by the service.
        if (event != null) {
            val isOutputKeyCode = keyCode in listOf(
                KeyEvent.KEYCODE_DPAD_UP,
                KeyEvent.KEYCODE_DPAD_DOWN,
                KeyEvent.KEYCODE_DPAD_LEFT,
                KeyEvent.KEYCODE_DPAD_RIGHT,
                KeyEvent.KEYCODE_TAB,
                KeyEvent.KEYCODE_PAGE_UP,
                KeyEvent.KEYCODE_PAGE_DOWN,
                KeyEvent.KEYCODE_ESCAPE
            )
            val hasModifiers = event.isAltPressed || event.isShiftPressed || event.isCtrlPressed

            // Ignore output keycodes without modifiers (they are generated by the service)
            if (!isOutputKeyCode || hasModifiers) {
                KeyboardEventTracker.notifyKeyEvent(keyCode, event, "KEY_UP", origin = "activity")
            }
        }
        return super.onKeyUp(keyCode, event)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Ship opinionated defaults on first run (once).
        SettingsManager.applyImpactDefaultsIfNeeded(this)

        // Check if tutorial has been completed
        if (!SettingsManager.isTutorialCompleted(this)) {
            val intent = Intent(this, TutorialActivity::class.java)
            startActivity(intent)
            finish()
            return
        }

        if (
            BuildConfig.RELEASE_CHANNEL != "nightly" &&
            SettingsManager.shouldShowWhatsNew(this, BuildConfig.VERSION_NAME)
        ) {
            val intent = Intent(this, TutorialActivity::class.java).apply {
                putExtra(TutorialActivity.EXTRA_UPDATE_TUTORIAL, true)
            }
            startActivity(intent)
            finish()
            return
        }

        if (shouldUseGithubUpdateChecks(this)) {
            // Schedule periodic background update checks (every 24 hours).
            UpdateCheckWorker.schedule(applicationContext)
        }

        enableEdgeToEdge()
        setContent {
            PastieraTheme {
                Box(modifier = Modifier.fillMaxSize()) {
                    Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                        KeyboardSetupScreen(
                            modifier = Modifier
                                .padding(innerPadding)
                                .fillMaxSize(),
                            activity = this@MainActivity
                        )
                    }

                    // Status bar overlay - responsive to theme
                    val statusBarHeight = WindowInsets.statusBars.asPaddingValues().calculateTopPadding()
                    val isDarkTheme = isSystemInDarkTheme()
                    val overlayColor = if (isDarkTheme) {
                        Color.Black.copy(alpha = 0.3f)
                    } else {
                        Color.White.copy(alpha = 0.2f)
                    }

                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(statusBarHeight)
                            .background(overlayColor)
                    )
                }
            }
        }
    }
}

private data class HomeUpdateInfo(
    val version: String,
    val downloadUrl: String?,
    val releasePageUrl: String?
)

private data class HomeTile(
    val icon: androidx.compose.ui.graphics.vector.ImageVector,
    val label: String,
    val onClick: () -> Unit,
    val attention: Boolean = false,
    val sublabel: String? = null
)

/**
 * Home = an action surface. It shows only what needs the user's attention
 * (enable / select / update), collapses to a single "✓ all set" line when
 * everything is fine, and offers a compact quick-launcher row. The physical
 * key-event logger now lives in Settings → Advanced → Diagnostics.
 */
@Composable
fun KeyboardSetupScreen(
    modifier: Modifier = Modifier,
    activity: MainActivity
) {
    val context = LocalContext.current

    var isPastieraEnabled by remember { mutableStateOf(false) }
    var isPastieraSelected by remember { mutableStateOf(false) }
    var enabledLanguageCount by remember { mutableStateOf(0) }
    var updateInfo by remember { mutableStateOf<HomeUpdateInfo?>(null) }

    // Smart-backlight readiness — surfaced on the Backlight tile so the home can flag
    // when the light is enabled but can't actually arm (needs pairing / Wi-Fi debug).
    var backlightEnabled by remember { mutableStateOf(false) }
    var backlightPaired by remember { mutableStateOf(false) }
    var backlightWirelessOn by remember { mutableStateOf(false) }

    fun refreshStatus() {
        checkImeStatus(context) { enabled, selected ->
            isPastieraEnabled = enabled
            isPastieraSelected = selected
        }
        enabledLanguageCount = getEnabledInputLanguageCount(context)
        backlightEnabled = SettingsManager.getSmartBacklightEnabled(context)
        backlightPaired = EmbeddedAdbShell.isPaired(context)
        backlightWirelessOn = EmbeddedAdbShell.isWirelessDebuggingEnabled(context)
    }

    // Initial IME + language + backlight status
    LaunchedEffect(Unit) { refreshStatus() }

    // Refresh status periodically while the screen is visible (kept from the old home).
    LaunchedEffect(Unit) {
        while (true) {
            delay(2000)
            refreshStatus()
        }
    }

    // Backlight attention: enabled but not actually able to light up yet.
    val backlightNeedsPairing = backlightEnabled && !backlightPaired
    val backlightNeedsWireless = backlightEnabled && backlightPaired && !backlightWirelessOn
    val backlightNeedsAttention = backlightNeedsPairing || backlightNeedsWireless

    // Request notification permission (Android 13+)
    val requestPermissionLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.RequestPermission()
    ) { /* result ignored */ }
    LaunchedEffect(Unit) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            if (!NotificationHelper.hasNotificationPermission(context)) {
                requestPermissionLauncher.launch(android.Manifest.permission.POST_NOTIFICATIONS)
            }
        }
    }

    // Automatic update check on open. Existing dialog behaviour is preserved AND
    // the result is surfaced as an action card.
    if (shouldUseGithubUpdateChecks(context)) {
        LaunchedEffect(Unit) {
            checkForUpdate(
                context = context,
                currentVersion = BuildConfig.VERSION_NAME,
                releaseChannel = BuildConfig.RELEASE_CHANNEL,
                ignoreDismissedReleases = true
            ) { hasUpdate, latestVersion, downloadUrl, releasePageUrl ->
                if (hasUpdate && latestVersion != null) {
                    updateInfo = HomeUpdateInfo(latestVersion, downloadUrl, releasePageUrl)
                    showUpdateDialog(context, latestVersion, downloadUrl, releasePageUrl)
                }
            }
        }
    }

    val launchSettings: (String?) -> Unit = { destination ->
        val intent = Intent(context, SettingsActivity::class.java)
        if (destination != null) {
            intent.putExtra(SettingsActivity.EXTRA_DESTINATION, destination)
        }
        context.startActivity(intent)
        (context as? Activity)?.let { act ->
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
                act.overrideActivityTransition(
                    Activity.OVERRIDE_TRANSITION_OPEN,
                    R.anim.slide_in_from_right,
                    0
                )
            } else {
                @Suppress("DEPRECATION")
                act.overridePendingTransition(R.anim.slide_in_from_right, 0)
            }
        }
    }

    val launchKeyboardTheme: () -> Unit = {
        launchSettings(SettingsActivity.DESTINATION_KEYBOARD_THEME)
    }

    Column(
        modifier = modifier
            .fillMaxWidth()
            .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        // Terminal header — physiboard:~$ prompt + blinking cursor.
        CustomTopBar(
            modifier = Modifier.fillMaxWidth()
        )

        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp)
        ) {
            val update = updateInfo

            // Setup action cards — shown only when action is required.
            when {
                !isPastieraEnabled -> HomeActionCard(
                    icon = Icons.Filled.Keyboard,
                    title = stringResource(R.string.home_action_enable_title),
                    subtitle = stringResource(R.string.home_action_enable_subtitle),
                    onClick = {
                        context.startActivity(Intent(Settings.ACTION_INPUT_METHOD_SETTINGS))
                    }
                )
                !isPastieraSelected -> HomeActionCard(
                    icon = Icons.Filled.Keyboard,
                    title = stringResource(R.string.home_action_select_title),
                    subtitle = stringResource(R.string.home_action_select_subtitle),
                    onClick = {
                        val imm = context.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
                        imm.showInputMethodPicker()
                    }
                )
            }

            if (update != null) {
                HomeActionCard(
                    icon = Icons.Filled.Update,
                    title = stringResource(R.string.home_action_update_title),
                    subtitle = stringResource(R.string.home_action_update_subtitle, update.version),
                    onClick = {
                        showUpdateDialog(context, update.version, update.downloadUrl, update.releasePageUrl)
                    }
                )
            }

            // All-clear: a single quiet mono line.
            if (isPastieraEnabled && isPastieraSelected && update == null) {
                Text(
                    text = stringResource(R.string.home_all_set),
                    style = MaterialTheme.typography.bodyMedium,
                    fontFamily = FontFamily.Monospace,
                    color = MaterialTheme.colorScheme.primary,
                    modifier = Modifier.padding(vertical = 4.dp)
                )
            }

            // Quick-launcher tiles. Wrap to 2 columns so they fit the square screen.
            val backlightSublabel = when {
                backlightNeedsPairing -> stringResource(R.string.home_tile_backlight_needs_setup)
                backlightNeedsWireless -> stringResource(R.string.home_tile_backlight_wireless_off)
                else -> null
            }
            val tiles = buildList {
                add(
                    HomeTile(
                        icon = Icons.Filled.LightMode,
                        label = stringResource(R.string.home_tile_backlight),
                        attention = backlightNeedsAttention,
                        sublabel = backlightSublabel,
                        onClick = { launchSettings(SettingsActivity.DESTINATION_SMART_BACKLIGHT) }
                    )
                )
                add(
                    HomeTile(
                        icon = Icons.Filled.Palette,
                        label = stringResource(R.string.home_tile_theme),
                        onClick = launchKeyboardTheme
                    )
                )
                add(
                    HomeTile(
                        icon = Icons.Filled.Mic,
                        label = stringResource(R.string.home_tile_voice),
                        onClick = { launchSettings(SettingsActivity.DESTINATION_VOICE) }
                    )
                )
                add(
                    HomeTile(
                        icon = Icons.Filled.AutoAwesome,
                        label = stringResource(R.string.home_tile_smart_features),
                        onClick = { launchSettings(SettingsActivity.DESTINATION_SMART_FEATURES) }
                    )
                )
                add(
                    HomeTile(
                        icon = Icons.Filled.Spellcheck,
                        label = stringResource(R.string.home_tile_auto_correct),
                        onClick = { launchSettings(SettingsActivity.DESTINATION_AUTO_CORRECT) }
                    )
                )
                add(
                    HomeTile(
                        icon = Icons.Filled.Code,
                        label = stringResource(R.string.home_tile_raw_mode),
                        onClick = { launchSettings(SettingsActivity.DESTINATION_RAW_MODE) }
                    )
                )
                add(
                    HomeTile(
                        icon = Icons.Filled.Keyboard,
                        label = stringResource(R.string.home_tile_fn_layer),
                        onClick = { launchSettings(SettingsActivity.DESTINATION_FN_LAYER) }
                    )
                )
                add(
                    HomeTile(
                        icon = Icons.Filled.Settings,
                        label = stringResource(R.string.home_tile_all_settings),
                        onClick = { launchSettings(null) }
                    )
                )
                if (enabledLanguageCount > 1) {
                    add(
                        HomeTile(
                            icon = Icons.Filled.Language,
                            label = stringResource(R.string.home_tile_language),
                            onClick = { launchSettings(SettingsActivity.DESTINATION_INPUT_LANGUAGES) }
                        )
                    )
                }
            }

            tiles.chunked(2).forEach { rowTiles ->
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(IntrinsicSize.Min),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    rowTiles.forEach { tile ->
                        HomeQuickTile(
                            icon = tile.icon,
                            label = tile.label,
                            attention = tile.attention,
                            sublabel = tile.sublabel,
                            modifier = Modifier.weight(1f),
                            onClick = tile.onClick
                        )
                    }
                    // Keep tile width consistent on an odd final row.
                    if (rowTiles.size == 1) Spacer(modifier = Modifier.weight(1f))
                }
            }
        }
    }
}

@Composable
private fun HomeActionCard(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    title: String,
    subtitle: String,
    onClick: () -> Unit
) {
    Surface(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onClick),
        color = MaterialTheme.colorScheme.surface,
        shape = MaterialTheme.shapes.medium
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 14.dp, vertical = 14.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            Icon(
                imageVector = icon,
                contentDescription = null,
                tint = MaterialTheme.colorScheme.primary,
                modifier = Modifier.size(22.dp)
            )
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = title,
                    style = MaterialTheme.typography.titleMedium,
                    fontFamily = FontFamily.Monospace,
                    fontWeight = FontWeight.Medium,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
                Text(
                    text = subtitle,
                    style = MaterialTheme.typography.bodySmall,
                    fontFamily = FontFamily.Monospace,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
            }
            Icon(
                imageVector = Icons.AutoMirrored.Filled.ArrowForward,
                contentDescription = null,
                tint = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.size(18.dp)
            )
        }
    }
}

@Composable
private fun HomeQuickTile(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    label: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    attention: Boolean = false,
    sublabel: String? = null
) {
    Box(modifier = modifier) {
        Surface(
            modifier = Modifier
                .fillMaxWidth()
                // Fill the row height (rows use IntrinsicSize.Min) so both tiles in a row
                // match — the Backlight "needs setup" sublabel no longer makes it taller than
                // its row-mate — while staying compact/content-sized so the grid fits.
                .fillMaxHeight()
                .heightIn(min = 64.dp)
                .clickable(onClick = onClick),
            color = MaterialTheme.colorScheme.surface,
            shape = MaterialTheme.shapes.medium
        ) {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 8.dp, vertical = 12.dp),
                verticalArrangement = Arrangement.spacedBy(6.dp, Alignment.CenterVertically),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Icon(
                    imageVector = icon,
                    contentDescription = null,
                    tint = MaterialTheme.colorScheme.primary,
                    modifier = Modifier.size(24.dp)
                )
                Text(
                    text = label,
                    style = MaterialTheme.typography.labelLarge,
                    fontFamily = FontFamily.Monospace,
                    fontWeight = FontWeight.Medium
                )
                if (sublabel != null) {
                    Text(
                        text = sublabel,
                        style = MaterialTheme.typography.labelSmall,
                        fontFamily = FontFamily.Monospace,
                        color = MaterialTheme.colorScheme.primary,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis
                    )
                }
            }
        }
        // Amber attention dot — the home's signal that the backlight needs a fix.
        if (attention) {
            Box(
                modifier = Modifier
                    .align(Alignment.TopEnd)
                    .padding(8.dp)
                    .size(9.dp)
                    .background(MaterialTheme.colorScheme.primary, CircleShape)
            )
        }
    }
}

/**
 * Counts the distinct language codes across PhysiBoard's enabled IME subtypes.
 * Used to decide whether the adaptive Language quick-tile is worth showing.
 */
private fun getEnabledInputLanguageCount(context: Context): Int {
    return try {
        val imm = context.getSystemService(Context.INPUT_METHOD_SERVICE) as? InputMethodManager
            ?: return 0
        val imeInfo = imm.enabledInputMethodList.find {
            it.packageName == ImeIdentity.packageName &&
                it.serviceName == ImeIdentity.serviceClassName
        } ?: return 0
        val enabledSubtypes = imm.getEnabledInputMethodSubtypeList(imeInfo, true)
        enabledSubtypes.mapNotNull { subtype ->
            val locale = subtype.localeString()
            if (!locale.isNullOrEmpty()) {
                try {
                    Locale.forLanguageTag(locale.replace("_", "-")).language.lowercase()
                } catch (_: Exception) {
                    locale.split("_").firstOrNull()?.lowercase()
                }
            } else {
                null
            }
        }.toSet().size
    } catch (e: Exception) {
        android.util.Log.e("MainActivity", "Error counting enabled input languages", e)
        0
    }
}

/**
 * Checks if Pastiera IME is enabled and selected.
 * Uses InputMethodManager for Android 14+ compatibility.
 */
private fun checkImeStatus(
    context: Context,
    callback: (enabled: Boolean, selected: Boolean) -> Unit
) {
    try {
        val imm = context.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
        val pastieraPackageName = ImeIdentity.packageName

        // Check if Pastiera is enabled using InputMethodManager
        val enabledInputMethods = imm.enabledInputMethodList
        val isEnabled = enabledInputMethods.any { inputMethodInfo ->
            inputMethodInfo.packageName == pastieraPackageName ||
            ImeIdentity.matchesImeId(inputMethodInfo.id)
        }

        // Check if Pastiera is selected
        var isSelected = false
        if (isEnabled) {
            try {
                val defaultInputMethod = android.provider.Settings.Secure.getString(
                    context.contentResolver,
                    android.provider.Settings.Secure.DEFAULT_INPUT_METHOD
                ) ?: ""
                isSelected = ImeIdentity.matchesImeId(defaultInputMethod)
            } catch (e: SecurityException) {
                // On Android 14+ (API 34+) with targetSdk 36, we can't read this setting.
                try {
                    val currentSubtype = imm.currentInputMethodSubtype
                    if (currentSubtype != null) {
                        val allInputMethods = imm.inputMethodList
                        val pastieraInputMethod = allInputMethods.find {
                            it.packageName == pastieraPackageName || ImeIdentity.matchesImeId(it.id)
                        }
                        isSelected = pastieraInputMethod != null && enabledInputMethods.size == 1
                    } else {
                        isSelected = false
                    }
                } catch (e2: Exception) {
                    isSelected = false
                }
            } catch (e: Exception) {
                isSelected = false
            }
        }

        callback(isEnabled, isSelected)
    } catch (e: Exception) {
        android.util.Log.e("MainActivity", "Error checking IME status", e)
        callback(false, false)
    }
}
