#!/usr/bin/env python3
"""Generates the skin-tone table the keyboard uses to tone an emoji, from Unicode's emoji-test.txt.

Source: Unicode Emoji 17.0 `emoji-test.txt` (Unicode License v3, see LICENSING.md). Download it with

    curl -sSfL -o emoji-test.txt https://www.unicode.org/Public/17.0.0/emoji/emoji-test.txt

sha256 of the 17.0 file this table was built from:
    1d8a944f88d7952f7ef7c5167fef3c67995bcae24543949710231b03a201acda

What it writes: one entry per emoji that takes a skin tone with every person in it wearing the
same tone, as "<untoned fully-qualified form> <light-toned form>". The other four tones are the
light form with U+1F3FB replaced by the tone's modifier; the script checks that every one of those
replacements is itself a fully-qualified sequence in the file, and fails if one is not, so the
rule the keyboard applies is exact for every entry it lists. Emoji whose toned forms exist only
with mixed tones (the 🫱‍🫲 handshake pairs) are not listed: they have no untoned fully-qualified
form to start from.

Usage:
    python3 -I scripts/build_skin_tone_table.py /path/emoji-test.txt \\
        core/actions/src/main/kotlin/brobata/physiboard/core/actions/emoji/SkinToneTable.kt

Requires only the Python standard library.
"""
import re
import sys

TONES = [0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF]
LIGHT = TONES[0]
VS16 = 0xFE0F
LINE = re.compile(r"^([0-9A-F ]+?)\s*;\s*fully-qualified\s*#")


def key(cps):
    """The lookup key: the code points without tones or VS16, so ☝ and ☝️ find the same entry."""
    return tuple(c for c in cps if c not in TONES and c != VS16)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    source, out = sys.argv[1], sys.argv[2]
    untoned = {}
    toned = set()
    order = []
    with open(source, encoding="utf-8") as f:
        for raw in f:
            m = LINE.match(raw)
            if not m:
                continue
            cps = tuple(int(c, 16) for c in m.group(1).split())
            if any(c in TONES for c in cps):
                if len(cps) == 1:
                    continue  # the five modifiers themselves are listed as components, not here
                toned.add(cps)
            else:
                k = key(cps)
                if k not in untoned:
                    untoned[k] = cps
                    order.append(k)
    entries = []
    for k in order:
        base = untoned[k]
        lights = [t for t in toned if key(t) == k and all(c == LIGHT for c in t if c in TONES)]
        if not lights:
            continue
        if len(lights) != 1:
            sys.exit(f"more than one uniform light form for {base!r}: {lights!r}")
        light = lights[0]
        for tone in TONES[1:]:
            other = tuple(tone if c == LIGHT else c for c in light)
            if other not in toned:
                sys.exit(f"{''.join(map(chr, other))!r} is not a fully-qualified sequence")
        entries.append(("".join(map(chr, base)), "".join(map(chr, light))))
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/build_skin_tone_table.py from Unicode Emoji 17.0 emoji-test.txt.\n")
        f.write("// Unicode License v3; see LICENSING.md. Do not edit by hand.\n")
        f.write("package brobata.physiboard.core.actions.emoji\n\n")
        f.write("/**\n")
        f.write(" * Every emoji that takes one skin tone for all its people: \"<untoned> <light-toned>\", one per\n")
        f.write(" * entry, in emoji-test.txt order. The other four tones replace U+1F3FB in the light form.\n")
        f.write(" */\n")
        f.write("internal object SkinToneTable {\n")
        f.write(f"    const val SIZE: Int = {len(entries)}\n\n")
        # Split into chunks so no single string constant nears the class file's 64 KB limit.
        chunk = 60
        f.write("    val ENTRIES: List<String> = listOf(\n")
        for i in range(0, len(entries), chunk):
            body = "\n".join(f"{b} {l}" for b, l in entries[i:i + chunk])
            f.write(f'        """\n{body}\n""",\n')
        f.write("    ).flatMap { chunk -> chunk.lines().filter { it.isNotBlank() } }\n")
        f.write("}\n")
    print(f"{len(entries)} toneable emoji written to {out}")


if __name__ == "__main__":
    main()
